import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("password"),
      isAdmin: true,
    },
    {
      name: "Mehedi",
      email: "mehedi@example.com",
      password: bcrypt.hashSync("password"),
      isAdmin: true,
    },
    {
      name: "User",
      email: "user@example.com",
      password: bcrypt.hashSync("password"),
      isAdmin: false,
    },
    {
      name: "Use",
      email: "use@example.com",
      password: bcrypt.hashSync("password"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Product 1",
      slug: "product-1",
      category: "shirts",
      img: "/images/iphone-12.jpg",
      brand: "nike",
      price: 10000,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular product",
    },
    {
      name: "Product 2",
      slug: "product-2",
      category: "shirts",
      img: "/images/iphone-13.webp",
      brand: "nike",
      price: 12000,
      rating: 4.3,
      numReviews: 7,
      countInStock: 25,
      description: "A popular product 2",
    },
    {
      name: "Product 3",
      slug: "product-3",
      category: "tshirts",
      img: "/images/iphone-14.jpg",
      brand: "signal",
      price: 14000,
      rating: 4.4,
      numReviews: 8,
      countInStock: 22,
      description: "A popular product 3",
    },
    {
      name: "Product 4",
      slug: "product-4",
      category: "shirts",
      img: "/images/samsung-as2.jpg",
      brand: "easy",
      price: 8000,
      rating: 4.8,
      numReviews: 8,
      countInStock: 18,
      description: "A popular product 4",
    },
    {
      name: "Product 5",
      slug: "product-5",
      category: "tshirts",
      img: "/images/oppo-a1k.jpg",
      brand: "holistar",
      price: 10000,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular product 5",
    },
    {
      name: "Product 6",
      slug: "product-6",
      category: "tshirts",
      img: "/images/oppo-f21-pro.jpg",
      brand: "easy",
      price: 8000,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular product 6",
    },
    {
      name: "Product 7",
      slug: "product-7",
      category: "pants",
      img: "/images/pants-1.png",
      brand: "holistar",
      price: 9000,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular product 5",
    },
  ],
};

export default data;
